// Wrangler の型生成を、待ち受けポートを使わず workerd の test エントリーポイントで行う。
import { mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const root = new URL("../", import.meta.url);
const cwd = fileURLToPath(root);
const env = { ...process.env, WRANGLER_SEND_METRICS: "false", WRANGLER_LOG_PATH: join(tmpdir(), "englishteacher-wrangler-types.log") };
const project = spawnSync(process.execPath, [join(cwd, "node_modules/wrangler/bin/wrangler.js"),
  "types", "--include-runtime=false", "--strict-vars=false"], { cwd, env, stdio: "inherit" });
if (project.status !== 0) process.exit(project.status ?? 1);
const folder = await mkdtemp(join(tmpdir(), "englishteacher-types-"));
try {
  const source = await readFile(require.resolve("workerd/worker.mjs"), "utf8");
  await writeFile(join(folder, "types.mjs"), source);
  await writeFile(join(folder, "main.mjs"), `
import generator from "./types.mjs";
export default {
  async test() {
    const response = await generator.fetch(new Request("http://types.invalid/2026-09-18+no_nodejs_compat+no_nodejs_compat_v2"));
    if (!response.ok) throw new Error(await response.text());
    console.log("ENGLISH_TEACHER_TYPES_BEGIN\\n" + await response.text() + "\\nENGLISH_TEACHER_TYPES_END");
  }
};`);
  const schema = require.resolve("workerd/workerd.capnp");
  await writeFile(join(folder, "types.capnp"), `
using Workerd = import ${JSON.stringify(schema)};
const config :Workerd.Config = (
  services = [(name = "types", worker = (
    compatibilityDate = "2024-01-01",
    compatibilityFlags = ["nodejs_compat", "rtti_api"],
    modules = [
      (name = "main.mjs", esModule = embed "main.mjs"),
      (name = "types.mjs", esModule = embed "types.mjs")
    ]
  ))]
);`);
  const binary = require("workerd").default;
  const result = spawnSync(binary, ["test", join(folder, "types.capnp"), "--experimental", "--import-path=/"], {
    encoding: "utf8", maxBuffer: 8 * 1024 * 1024, env,
  });
  const output = result.stdout + result.stderr;
  const match = /ENGLISH_TEACHER_TYPES_BEGIN\n([\s\S]*?)\nENGLISH_TEACHER_TYPES_END/.exec(output);
  if (result.status !== 0 || !match) throw new Error(`Runtime types failed:\n${output.slice(0, 4000)}`);
  const file = new URL("worker-configuration.d.ts", root);
  const projectTypes = await readFile(file, "utf8");
  // Env に足す2つは wrangler の生成に任せない。
  //   GEMINI_API_KEY は Worker の secret で、値は wrangler.jsonc に無い。名前を知るには
  //   上流への問い合わせか手元の .dev.vars が要り、CI(APIトークンだけ、.dev.vars 無し)では
  //   どちらも無いので型から落ちて cf:check が落ちる。secret は本番に必ずあるので、ここで宣言する。
  //   LOCAL_DEV は cf:dev のときだけ入る印。
  await writeFile(file, projectTypes + "\n// Runtime types generated by the installed workerd.\n" + match[1] +
    "\ninterface Env { GEMINI_API_KEY: string; LOCAL_DEV?: string; }\n");
  console.log("Cloudflare types generated without opening a listening socket.");
} finally {
  await rm(folder, { recursive: true, force: true });
}
