import { readFile, readdir, mkdir, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const promptDir = new URL("server/prompts/", root);
const sceneDir = new URL("server/scenes/", root);
const outputDir = new URL("server/src/generated/", root);
const [promptNames, sceneNames] = await Promise.all([
  readdir(promptDir), readdir(sceneDir),
]);
const prompts = Object.fromEntries(await Promise.all(
  promptNames.filter(name => name.endsWith(".md")).sort().map(async name =>
    [name, (await readFile(new URL(name, promptDir), "utf8")).trim()]),
));
const scenes = await Promise.all(sceneNames.filter(name => name.endsWith(".json")).sort().map(async name => ({
  id: name.slice(0, -5), data: JSON.parse(await readFile(new URL(name, sceneDir), "utf8")),
})));
const content = "// Generated by scripts/generate-content.mjs. Edit server/prompts/ and server/scenes/ instead.\n" +
  `export const promptTemplates: Readonly<Record<string, string>> = ${JSON.stringify(prompts, null, 2)};\n` +
  `export const bundledScenes = ${JSON.stringify(scenes, null, 2)};\n`;
await mkdir(outputDir, { recursive: true });
const output = new URL("content.ts", outputDir);
if (await readFile(output, "utf8").catch(() => "") !== content) await writeFile(output, content);
